trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  CI: true

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js 20'

  - script: |
      npm ci
      npm run build
      npm run test # Asegúrate de tener scripts de prueba
    displayName: 'Install, build and test'
    env:
      NEXT_PUBLIC_ENV: test

  - script: |
      echo "##vso[task.setvariable variable=BUILD_STATUS]success"
      echo "Build completed successfully - Ready for Vercel deployment"
    displayName: 'Set build status'
    condition: succeeded()